<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://localhost:8080/assets/css/signin.css" rel="stylesheet">
    <link href="http://localhost:8080/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://localhost:8080/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>

<body class="text-center">

    <main class="form-signin">
        <div class="alert" id="message" role="alert">
        </div>
        <i class="bi bi-person-circle mb-4 login-icon"></i>
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

        <div class="form-floating mt-3">
            <input type="email" class="form-control" name="email" id="email" placeholder="name@example.com" required>
            <label for="email">Email address</label>
            <small class="text-danger" id="errorEmail"></small>
        </div>
        <div class="form-floating mt-3">
            <input type="password" class="form-control" name="password" id="password" placeholder="Password" required>
            <label for="password">Password</label>
            <small class="text-danger" id="errorPassword"></small>
        </div>
        <button class="w-100 btn btn-lg btn-primary" id="login">Sign in</button>
        <div class="mb-3 mt-4">
            <label>
                Don't have an account <a href="signup">sign up</a>
            </label>
        </div>
        <a href="#">Forgot password</a>
    </main>
    <script src="http://localhost:8080/assets/js/requests.js"></script>
</body>


</html>