<footer>
        <div id="footer" class="blog-footer bg-dark">
            <div id="footer-nav" class="row">
                <p id="footer-logo" class="h3 nav justify-content-start text-success d-inline-block mx-5">Blog</p>
                <ul class="nav justify-content-end text-light">

                    <li class="nav-item m-3"><a href="#"><i class="bi bi-instagram text-warning"></i></a></li>
                    <li class="nav-item m-3"><a href="#"><i class="bi bi-twitter text-primary"></i></a></li>
                    <li class="nav-item m-3"><a href="#"><i class="bi bi-youtube text-danger"></i></a></li>
                    <li class="nav-item m-3"><a href="#"><i class="bi bi-whatsapp text-success"></i></a></li>
                </ul>
            </div>

            <div class="row text-light m-3">
                <div class="col-md-3">
                    <p class="h3">Start crafting epic <span class="h2">websites</span> today</p>
                </div>

                <div class="col-md-3">
                    <p>Useful</p>
                    <p>Documentation intro video showcase buy them</p>
                </div>

                <div class="col-md-3">
                    <p>Keep in touch</p>
                    <p>Nippon, Osaka, Crimson street 78-42<br><span>support@brand.com</span></p>
                </div>

                <div class="col-md-3">
                    <p>Sign up for news letter</p>
                    <p class="d-inline-flex">
                        <input type="email" class="form-control-plaintext w-50 p-2 bg-light" id="staticEmail2" placeholder="Email address">
                        <button type="button" id="newsLetterBtn" class="w-25 btn btn-success">Send</button>
                    </p>
                </div>

            </div>

            <div class="row text-light m-3 pb-xxl-5">
                <div class="col">
                    <p class="d-inline float-left">@ 2021 javeline crafted</p>
                    <ul class="d-inline float-end">
                        <li class="d-inline float-left p-2">privacy policy</li>
                        <li class="d-inline float-left p-2">Terms & condition</li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    </body>

    </html>