<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <!-- Bootstrap core CSS -->
    <link href="http://localhost:8080/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="http://localhost:8080/assets/css/blog.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

</head>

<body>

    <div class="container-fluid">
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand h1 mt-1 text-success" href="http://localhost:8080">Tech Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">

                    <ul class="navbar-nav mr-auto align-items-end">

                        <li class="nav-item active">
                            <a class="nav-link" href="/">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="index/write">Write a Blog</a>
                        </li>
                    </ul>
                    <?php if (!isset($currentUser)) : ?>
                        <a type="button" class="btn btn-outline-success mx-1" href="login">Login/SignUp </a>
                    <?php else : ?>
                        <a class="nav-link text-info name" href="http://localhost:8080/admin"><?php echo $currentUser['name']; ?></a>
                        <a class="nav-link text-warning" href="http://localhost:8080/login/logout">Logout</a>

                    <?php endif ?>

                </div>
            </nav>

        </header>


    </div>