<?php

echo "<h1>Hello World</h1>";

echo PHP_EOL;

echo $this->tag->linkTo(
    'signup',
    'Sign Up Here!'
);
// print_r(json_encode($users));
if ($users->count()>0) {
?>
<table class="table table-bordered table-hover">
    <tr>
       <th>ID</th> 
       <th>Name</th> 
       <th>Email</th> 
    </tr>
    <?php foreach ($users as $user) { ?>
        <tr>
            <td><?php echo $user->id ?></td>
            <td><?php echo $user->name ?></td>
            <td><?php echo $user->email ?></td>
        </tr>
    <?php } ?>
</table>
<?php } ?>