<?php require_once('header.phtml'); ?>
<main>
    <div class="container">
        <div class="row mt-5">
            <h1 class="text-center text-success bg-info">Write a blog on your favourite topic</h1><hr>
            <div class="alert alert-<?php echo $success === true ? 'success' : ''; ?>">
                <?php if ($success === true) echo $message; ?>
            </div>

            </div>
            <form method="POST" action="">
                <div class="row">
                    <div class="col-sm-4">
                        <lable for="category_id">Categories</lable>
                        <select class="form-select" name="category_id" id="catId">
                            <option name="" selected></option>
                            <?php
                            //print_r($data);
                            foreach ($category as $val) {
                                echo '<option value="'.$val->category_id.'">'.$val->category_name.'</option>';
                            }
                            ?>
                        </select>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control px-2" name="post_topic" id="post_topic" placeholder="Blog title" required>
                        <label for="post_topic">Blog topic</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control px-2" name="post_title" id="post_title" placeholder="Blog title" required>
                        <label for="post_title">Blog title</label>
                    </div>
                </div>
                <div class="row">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control px-2" name="post_description" id="post_description" placeholder="Blog title" required>
                        <label for="post_description">Blog Description</label>
                    </div>
                </div>
                <div class="row">
                    <div class="mb-3">
                        <label for="post_content" class="form-label">Write blog content</label>
                        <textarea class="form-control" name="post_content" id="post_content" rows="10"></textarea>
                    </div>
                </div>
                <div class="row mb-5 m-auto">
                    <button type="submit" class="btn btn-success btn-lg w-25">Publish Blog</button>
                </div>
            </form>
        </div>
    </div>
</main>
<?php require_once('footer.phtml');