<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://localhost:8080/assets/css/signin.css" rel="stylesheet">
    <link href="http://localhost:8080//node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://localhost:8080//node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
</head>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
</head>

<body class="text-center">

    <main class="form-signin">
        <i class="bi bi-person-circle login-icon"></i>
        <h1 class="h3 mb-2 fw-normal">Sign Up</h1>

        <div class="form-floating mt-2 text-left">
            <input type="text" class="form-control" id="name" placeholder="Enter your name">
            <label for="name">Full Name</label>
            <small class="text-danger" id="errorName"></small>
        </div>
        <div class="form-floating mt-3 text-left">
            <input type="email" class="form-control" id="email" placeholder="name@example.com">
            <label for="email">Email address</label>
            <small class="text-danger" id="errorEmail"></small>
        </div>
        <div class="form-floating mt-3 text-left">
            <input type="password" class="form-control" id="password" placeholder="Password">
            <label for="password">Password</label>
            <small class="text-danger" id="errorPassword"></small>
        </div>
        <div class="form-floating mt-3 text-left">
            <input type="password" class="form-control" id="confirmPassword" placeholder="Confirm Password">
            <label for="confirmPassword">Confirm Password</label>
            <small class="text-danger" id="errorConfirmPassword"></small>
        </div>
        <button class="w-100 btn btn-lg btn-primary" id="signUp">Sign Up</button>
        <div class="alert" id="message" role="alert">
        </div>
        <div class="mb-3 mt-4">
            <label>
                Already have an account <a href="login">sign in</a>
            </label>
        </div>
    </main>
    <script src="http://localhost:8080/assets/js/requests.js"></script>
</body>


</html>